version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: junosixteen
      POSTGRES_USER: postgres
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mangle:
    build: ./services/mangle
    environment:
      MANGLE_FAKE: "1" # auf "0" setzen, wenn echte Mangle-API importiert ist
    ports: 
      - "7070:7070"
    volumes:
      - ./services/mangle/rules:/app/rules:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:7070/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/junosixteen?schema=public
      - MANGLE_URL=http://mangle:7070
      - NODE_ENV=development
      - PORT=5000
    depends_on:
      db:
        condition: service_healthy
      mangle:
        condition: service_healthy
    ports: 
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Optional: Adminer for database management
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  default:
    name: junosixteen-network 